config/routes.rb
GlossolHellYeah::Application.routes.draw do


  root to: "site#root"
  get 'auth/facebook/callback', to: "omniauth_callbacks#facebook"

  shallow do
    resources :users, only: [:create, :new, :edit, :update, :show, :destroy] do
      resources :documents
    end
    resource :session, only: [:create, :new, :destroy, :show]
    resources :documents do
      resources :stars, only: [:create, :destroy]
      resources :annotatings, only: [:create, :new]
      resources :references, only: [:new, :create]
    end
  end

  resources :annotatings, only: [:destroy]


 namespace :api do
    resource :session, only: [:create, :new, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    get "search/:query", to: "search#show"

    shallow do
      resources :users do
        resources :documents
      end
    end
    resources :documents, only: [:show, :index, :create] do
      resources :annotations
      resources :references
    end
  end
  
  get 'bb/', to: "site#root"
end

app/models/annotating.rb
class Annotating < ActiveRecord::Base
  serialize :source_text
  
  validates :source_document, :source_text, presence: true

  belongs_to(
    :source_document,
    class_name: "Document",
    foreign_key: :source_document_id
  )
  belongs_to(
    :annotation,
    class_name: "Document",
    foreign_key: :annotation_id
  )

  def text_selection
    text = self.source_document.body
    text[self.source_text.first.to_i..self.source_text.last.to_i]
  end
end

app/controllers/annotatings_controller.rb
class AnnotatingsController <ApplicationController


  def create
    if ref_params[:ref_text]
      ensure_current_is_author
      add_reference
    else
      add_annotation
    end
  end

  def new
    @docs = Document.all
    @document = Document.find(params[:document_id])
  end

  def destroy
    @annotating = Annotating.find(params[:id])
    annotation = @annotating.annotation
    if current_user = @annotating.annotation.author
      if @annotating.destroy
        add_notice("Reference successfully destroyed!")
        redirect_to document_url(annotation)
      else
        add_error(@annotating.errors.full_messages)
        redirect_to document_url(annotation)
      end
    else
      add_error("You can't destroy an annotation that isn't yours!")
      redirect_to document_url(annotation)
    end
  end


  private

  def doc_params
    params.require(:annotating).permit(:body, :title)
  end
  
  def ref_params
    params.require(:annotating).permit(:ref_text, :source_text)
  end

  

  def add_reference
    @annotating = Annotating.new(
      source_document_id: ref_params[:ref_text],
      annotation_id: params[:document_id],
      source_text: ref_params[:source_text].split
    )

    if @annotating.save
      add_notice("#{@annotating.text_selection} saved from
                          #{@annotating.source_document.title}")
    else
      add_error(@annotating.errors.full_messages)
    end
    redirect_to new_document_annotating_url(params[:document_id])
  end

  def add_annotation
    @document = current_user.documents.new(doc_params)

    if annotating_created
      redirect_to document_url(@document)
    else
      add_error(@document.errors.full_messages)
      add_error(@annotating.errors.full_messages) if @annotating
      redirect_to document_url(params[:document_id])
    end
  end
  
  def annotating_created
      @document.references.build(
              source_document_id: params[:document_id],
              source_text: ref_params[:source_text].split
            )
      @document.save
  end

  def ensure_current_is_author
    author = Document.find(params[:document_id]).author
    unless author == current_user
      add_error("You must be the author of a document to add references!")
      redirect_to root_path
    end
  end

end

app/views/annotatings/_anno_list.html.erb
<h2>Annotations</h2>

<% unless annotations.empty? %>
  <ul>
    <% annotations.each do |annotation| %>
      <li>
        <%= link_to annotation.title, document_url(annotation) %>
          by <%= annotation.author.email %>
      </li>
    <% end %>
  </ul>

<% else %>
  <h4>No Annotations Yet</h4>
<% end %>

app/views/annotatings/_form.html.erb
<form
  action="<%= document_annotatings_url(document) %>"
  method="POST"
  class="new-anno">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for "note-title">Annotation Title</label>
  <input type="text" name="annotating[title]" id="note-title">

  <br>

  <label for "note-body">Annotation Text</label>
  <textarea name="annotating[body]" id="note-body"></textarea>

  <br>

  <label for="selection">Start and Stop</label>
  <input type="text" name="annotating[source_text]" id="selection">

  <input type="submit" value="Create Annotation" id="c-annoter">
</form>

app/views/annotatings/_ref_delete.html.erb
<form action="<%= annotating_url(anno) %>" method="POST">

  <input type="hidden" name="_method" value="delete">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">


  <input type="submit" value="Delete Reference">
</form>

app/views/annotatings/_ref_form.html.erb
<form action="<%= document_annotatings_url(base_text) %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden"
    name="annotating[ref_text]"
    value="<%= ref %>">

  <label for="range">
  <input type="text" name="annotating[source_text]" id="range">

  <input type="submit" value="Add Reference">

</form>

app/views/annotatings/_ref_index.html.erb
<ul>
  <% docs.each do |doc| %>
    <li>
      <%= link_to doc.title, document_url(doc) %>
      written by: <%= doc.author.email%>
      <br>
      <p>
        <%= doc.body %>
      <p>
        <%= render "ref_form", ref: doc.id, base_text: @document %>
        <br>
        <br>
    </li>

  <% end %>
</ul>

app/views/annotatings/_ref_list.html.erb
<h2>Annotated Texts</h2>
<% unless references.empty? %>
  <ul>
    <% references.each do |reference| %>
      <li>
        <%= link_to reference.source_document.title, document_url(reference.source_document)%>:
        <p><%= reference.text_selection %></p>
        <% if current_author %>
          <div class="del-ref">
            <%= render "annotatings/ref_delete", anno: reference %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No Annotated Texts</p>
<% end %>

app/views/annotatings/new.html.erb
<h1>Add References</h1>
<h2>for <%= link_to @document.title, document_url(@document) %></h2>

<h1>Existing References:</h1>

<%= render "ref_list",
    references: @document.references,
    current_author: current_user == @document.author %>

<%= link_to "Done Adding References", document_url(@document) %>

<%= render "ref_index", docs: @docs %>