config/routes.rb
GlossolHellYeah::Application.routes.draw do


  root to: "site#root"
  get 'auth/facebook/callback', to: "omniauth_callbacks#facebook"

  shallow do
    resources :users, only: [:create, :new, :edit, :update, :show, :destroy] do
      resources :documents
    end
    resource :session, only: [:create, :new, :destroy, :show]
    resources :documents do
      resources :stars, only: [:create, :destroy]
      resources :annotatings, only: [:create, :new]
      resources :references, only: [:new, :create]
    end
  end

  resources :annotatings, only: [:destroy]


 namespace :api do
    resource :session, only: [:create, :new, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    get "search/:query", to: "search#show"

    shallow do
      resources :users do
        resources :documents
      end
    end
    resources :documents, only: [:show, :index, :create] do
      resources :annotations
      resources :references
    end
  end
  
  get 'bb/', to: "site#root"
end

app/models/document.rb
class Document < ActiveRecord::Base
  include PgSearch

  multisearchable against: [:title, :body]
  
  validates :title, uniqueness: true

  validates :title, :body, :user_id, presence: true
  belongs_to :author, class_name: "User", foreign_key: :user_id

  has_many(
    :annotatings,
    class_name: "Annotating",
    foreign_key: :source_document_id
  )

  has_many(
    :references,
    class_name: "Annotating",
    foreign_key: :annotation_id
  )

  has_many :annotations, through: :annotatings, source: :annotation
  has_many :referenced_texts, through: :references, source: :source_document

  has_many(
     :stars,
     class_name: "Star",
     foreign_key: :document_id,
     dependent: :destroy
  )

  has_many :fans, through: :stars, source: :user

  def parent
    self.referenced_texts.first
  end

end

app/controllers/api/documents_controller.rb
class Api::DocumentsController < ApplicationController

  def index

    if user_given?
      @documents = Document.where(' user_id = ?',
                   params[:user_id]).includes(:references, :annotatings)
    else
      @documents = Document.includes(:references, :annotatings).all
    end
              
    render "api/documents/index"
  end

  def show
    @document = Document.includes(:references, :annotatings).find(params[:id])
    render "api/documents/show"
  end
  
  
  def create
    
    @document = current_user.documents.new(doc_params)
    
    if ref_params
      #replace first with each block later
      @document.referenced_text_ids = ref_params.first[:referenced_text_ids]
      @document.references.last.source_text = ref_params.first[:source_text]
    end

    if @document.save
      id = @document.id
      @document = Document.includes(:references, :annotatings).find(id)
      render "api/documents/show"
    else
      p @document.errors
      render json: { status: :unprocessable_entity }
    end
  end


  private

  def doc_params
    params.require(:document).permit(:title, :body)
  end
  
  def ref_params
    params[:references]
  end
  
  def doc_is_annotation?
    !!params["references"]
  end
  
  def user_given?
    !!params[:user_id]
  end
      
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_action :ensure_owner, only: [:edit, :update, :destroy]
  before_action :verify_signed_in

  def index
    @my_documents = current_user.documents
  end

  def new
    @document = Document.new
  end

  def create
    @document = current_user.documents.new(doc_params)
    if @document.save
      redirect_to document_url(@document)
    else
      add_error(@document.errors.full_messages)
      render :new
    end
  end

  def update
    @document = Document.find(params[:id])
    if @document.update(doc_params)
      add_notice("#{@document.title} successfully updated!")
      redirect_to document_url(@document)
    else
      add_error(@document.errors.full_messages)
      redirect_to edit_document_url(@document)
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def destroy
    @document = Document.find(params[:id])
    if @document.annotations.empty?
      title = @document.title
      if @document.destroy
        add_notice("#{title} successfully destroyed!")
        redirect_to documents_url
      end
    else
      add_error("You can't delete a doc referenced by others. Sorry!")
      redirect_to documents_url
    end
  end

  def show
    @document = Document.find(params[:id])
  end


  private

  def doc_params
    params.require(:document).permit(:body, :title)
  end

  def ensure_owner
    unless current_owner = Document.find(params[:id]).author
      add_error("You must be the document's author to do that!")
      redirect_to documents_url
    end
  end

end

app/views/documents/_doc_delete.html.erb
<form action="<%= document_url(doc) %>" method="POST">

  <input type="hidden" name="_method" value="delete">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="submit" value="Delete Document" class="del-doc">
</form>

app/views/documents/_doc_info.html.erb
<h1><%= doc.title %></h1>
<div class="citer">
  <h2>Author:<h2> <h3><%= doc.author.email %></h3>
  <%= render "star", doc: doc %>
</div>

<div class="manipulate">
  <% if current_user == doc.author %>
    <%= link_to "Edit Document", edit_document_url(doc) %>
    <%= render "doc_delete", doc: doc %>
  <% end %>
</div>

app/views/documents/_form.html.erb
<% if doc.persisted? %>
  <% action = document_url(doc) %>
<% else %>
  <% action = user_documents_url(current_user) %>
<% end %>

<form action="<%= action %>" method="POST" class="doc-form">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <% if doc.persisted? %>
    <input type="hidden" name="_method" value="put">
  <% end %>
  
  <section class="utility-stuff group">
   
   <% if doc.persisted? %>
     <div class="submitter"><button>Update Document</button></div>
   <% else %>
    <div class="submitter"><button>Create Document</button></div>
    <% end %>
   
    <section class="title-stuff"> 
      <label for "doc-title">Title:</label>
      <input
        type="text"
        name="document[title]"
        id="doc-title"
        value="<%= doc.title %>">
    </section>
  </section>
    

  <section class="main-text">
    <label for "doc-body"></label>
    <textarea rows="40" cols="80" name="document[body]" id="doc-body">
      <%= doc.body %>
    </textarea>
  </section>
    
    

  

</form>

app/views/documents/_likes.html.erb
<ul>
  <% stars.each do |star| %>
    <li><%= star.user.display_name %> Starred This!</li>
  <% end %>
</ul>

app/views/documents/_star.html.erb
<!--This is not an error! -->

<% unless star = already_liked?(doc) %>

  <form action="<%= document_stars_url(doc) %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <input type="submit" value="Add Star to this Document" class="starling">
  </form>

<% else %>

  <h4>You Starred This!</h4>
  <form action="<%= star_url(star) %>" method="POST">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <input type="hidden" name="_method" value="DELETE">

    <input type="submit" value="Un-Star this Document" class="starling">
  </form>
<% end %>

app/views/documents/_title_list.html.erb
<section class="doc-list">
  <% unless documents.empty? %>
    <ul>
      <% documents.each do |doc| %>
        <li>
          <%= link_to doc.title, document_url(doc) %>
          <% if owner == true %>
            <div class="del-button"><%= render "doc_delete", doc: doc %></div>
          <% end %>
        </li>
      <% end %>
    </ul>
  
  <% else %>
  <p>No Docs Yet</p>
  
  <% end %>
  
</section>

app/views/documents/edit.html.erb
<h1>Edit <%= @document.title %></h1>

<%= link_to "Back to #{@document.title}", document_url(@document) %>
<%= render "form", doc: @document %>

app/views/documents/index.html.erb
<section class="docs group">

  <h1>Documents Index</h1>

  <br>
  <%= image_tag current_user.profile_pic.url(:small) if current_user.try(:profile_pic) %>
  <br>

  <div class="c-doc"><%= link_to "Create Document",
    new_user_document_url(current_user),
    class: "create-doc" %></div>

    <%= render "layouts/sign_out" %>

  <section class="all-docs group" >

    <section class="cu-docs ">
      <h3>My Documents</h3>
      <%= render "title_list", documents: @my_documents, owner: true %>
    </section>

    <section class="other-docs ">
      <h3>Other Documents</h3>
      <%= render "title_list", documents: sample_documents, owner: false %>
    </section>

  </section>



</section>

app/views/documents/new.html.erb
<section class="new-doc group">
  <h1>Create a New Document</h1>

  <%= render "form", doc:@document %>
</section>

app/views/documents/show.html.erb
<article class="doc-show group">

  <section class="meta-doc">
    
    <section class="forms group">
      <section class="doc-info group">
        <%= render "doc_info", doc: @document %>
      </section>
    
      <section class="anno-stuff grou">
    
        <section class="anno-form">
          <%= render "annotatings/form", document: @document %>
        </section>
      
        </section>
        
      </section>
    
    
    <section class="lists">
      <section class="anno-list">
        <%= render "annotatings/anno_list", annotations: @document.annotations %>
      </section>

    </section>
    
    <div class="ref-list">
      <%= render "annotatings/ref_list",
                  references: @document.references,
                  current_author: current_user == @document.author %>

      <% if current_user == @document.author %>
      <div class="add-ref">
        <%= link_to "Add References", new_document_annotating_url(@document) %>
      </div>
      <% end %>
      
      </div>
      

      <%= render "likes", stars: @document.stars.includes(:user) %>
  
    </section>
  </section>
  
  <section class="doc-text">
    <h2>Document Text:</h2>
    <div class="doc-body"><%= @document.body %></div>
  </section>
  
  
</article>