config/routes.rb
GlossolHellYeah::Application.routes.draw do


  root to: "site#root"
  get 'auth/facebook/callback', to: "omniauth_callbacks#facebook"

  shallow do
    resources :users, only: [:create, :new, :edit, :update, :show, :destroy] do
      resources :documents
    end
    resource :session, only: [:create, :new, :destroy, :show]
    resources :documents do
      resources :stars, only: [:create, :destroy]
      resources :annotatings, only: [:create, :new]
      resources :references, only: [:new, :create]
    end
  end

  resources :annotatings, only: [:destroy]


 namespace :api do
    resource :session, only: [:create, :new, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    get "search/:query", to: "search#show"

    shallow do
      resources :users do
        resources :documents
      end
    end
    resources :documents, only: [:show, :index, :create] do
      resources :annotations
      resources :references
    end
  end
  
  get 'bb/', to: "site#root"
end

app/controllers/api/references_controller.rb
class Api::ReferencesController < ApplicationController

  def index
    @doc = Document.find(params[:document_id])
    render "api/references"
  end
  
  def create
    @doc = Document.find(params[:document_id])
    @doc.references.new({
      source_text: params[:reference][:source_text],
      source_document_id: params[:reference][:source_document_id]
    })
    if @doc.save
      render json: @doc.references.last
    else
      binding.pry
    end
  end

end

app/views/references/_form.html.erb
<form action="<%= document_annotatings_url(base_text) %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden"
    name="annotating[ref_text]"
    value="<%= ref %>">

  <label for="range">
  <input type="text" name="annotating[source_text]" id="range">

  <input type="submit" value="Add Reference">

</form>

app/views/references/_ref_index.html.erb
<ul>
  <% docs.each do |doc| %>
    <li>
      <%= link_to doc.title, document_url(doc) %>
      written by: <%= doc.author.email%>
      <br>
      <p>
        <%= doc.body %>
      <p>
        <%= render "form", ref: doc.id, base_text: @document %>
        <br>
        <br>
    </li>

  <% end %>
</ul>