config/routes.rb
GlossolHellYeah::Application.routes.draw do


  root to: "site#root"
  get 'auth/facebook/callback', to: "omniauth_callbacks#facebook"

  shallow do
    resources :users, only: [:create, :new, :edit, :update, :show, :destroy] do
      resources :documents
    end
    resource :session, only: [:create, :new, :destroy, :show]
    resources :documents do
      resources :stars, only: [:create, :destroy]
      resources :annotatings, only: [:create, :new]
      resources :references, only: [:new, :create]
    end
  end

  resources :annotatings, only: [:destroy]


 namespace :api do
    resource :session, only: [:create, :new, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    get "search/:query", to: "search#show"

    shallow do
      resources :users do
        resources :documents
      end
    end
    resources :documents, only: [:show, :index, :create] do
      resources :annotations
      resources :references
    end
  end
  
  get 'bb/', to: "site#root"
end

app/views/layouts/_demo_user.html.erb
<form action="<%= session_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="hidden" name="user[email]" value="demo@demo.com">
  <input type="hidden" name="user[password]" value="drowssap">
  <input type="submit" value="Sign in as Demo User" class="nav-link">
</form>

app/views/layouts/_flash_messages.html.erb
<ul>
  <% unless messages.nil? %>
    <% messages.each do |message| %>
     <li><h2><%= message %></h2></li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/_sign_out.html.erb
<form action="<%= session_url %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="submit" value="Sign Out" class="nav-link">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlossolGenius</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,600,800|Montserrat:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,600&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

  <nav class="group">
    
    <container class="nav-logo group">
      <%= image_tag "mini_logo.png", class: "logo-img" %>
      <div class="app-title">glossolGenius</div>
    </container>
   
    <container class="links group">
      <% if signed_in? %>
      
      <ul class="getting-around group">
        <li>
          <%= link_to "Home", user_documents_url(current_user), class: "nav-link"%>
        </li>
        <li>
          <%= link_to "Settings", edit_user_url(current_user), class: "nav-link"%>
        </li>
        <li><%= render "layouts/sign_out" %></li>
      </ul>
      
      <% else %>
      
      <ul class="entrance group">
        <li><%= link_to "Sign In", new_session_url, class: "nav-link" %></li>
        <li><%= link_to "Sign Up", new_user_url, class: "nav-link" %></li>
        <li><%= render "layouts/demo_user" %></li>
      </ul>
      
      <% end %>
    
    </container>
  </nav>

  <section class="errors">
    <div class="error">
      <%= render "layouts/flash_messages", messages: flash[:errors] %>
    </div>
    <div class="notice">
      <%= render "layouts/flash_messages", messages: flash[:notices] %>
    </div>
  </section>


  <main>
    <%= yield %>
  </main>
  
 

</body>
</html>